#!/usr/bin/env bash
#
# install.sh — make this Obsidian vault's .claude the source of truth for ~/.claude
#
# Model: PER-ITEM symlinks. The vault holds the real files (git-tracked = SoT);
#        each ~/.claude/<category>/<item> and each top-level config file becomes a
#        symlink pointing into the vault. The whole ~/.claude dir is NEVER symlinked,
#        so runtime state (projects/, sessions/, cache/, credentials, plugins/, ...)
#        is untouched by construction.
#
# Paths: vault-tracked files never hardcode an absolute path — they write the
#        placeholders {base_url} (vault root) and {home}. This script resolves both
#        for THIS machine into ~/.claude/rules/00-machine-paths.md, which loads with
#        every session. That file is generated, machine-local, and never migrated
#        back into the vault.
#
# Profile: PROFILE=work|personal|all selects which skills get linked. Skills for the
#        other profile are pruned (only symlinks that point into the vault are ever
#        removed). Common skills install under every profile.
#
# Safe:  idempotent, backs up anything it replaces to ~/.claude/backups/install-<stamp>/,
#        and defaults to DRY-RUN. Apply with:  DRY_RUN=0 PROFILE=personal ./install.sh
#
set -euo pipefail
shopt -s nullglob

VAULT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VAULT_CLAUDE="$VAULT_ROOT/.claude"
HOME_CLAUDE="$HOME/.claude"
STAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP="$HOME_CLAUDE/backups/install-$STAMP"
DRY_RUN="${DRY_RUN:-1}"
PROFILE="${PROFILE:-all}"

case "$PROFILE" in
  work|personal|all) ;;
  *) echo "install.sh: PROFILE must be work|personal|all (got '$PROFILE')" >&2; exit 2 ;;
esac

# Category dirs linked per-item; single top-level config files linked individually.
CATEGORIES=(skills rules hooks agents commands)
TOP_FILES=(CLAUDE.md keybindings.json settings.json)
# Loose junk under skills/ to delete (not real skills — no own folder).
SKILL_JUNK=(SKILL.md STYLE_PRESETS.md)
# Never touched anywhere: noise, or generated by this script.
ALWAYS_SKIP=(. .. .DS_Store)
MACHINE_PATHS_REL="rules/00-machine-paths.md"
# Never symlinked: machine-local by Claude Code convention.
# (settings.local.json is intentionally excluded from TOP_FILES above.)

# --- skill profiles ---------------------------------------------------------
# Installed under every profile.
COMMON_SKILLS=(code-reviewer repo-router cook-loop cook-staging)
# Company / client work only.
WORK_SKILLS=(
  jira-automation internal-service-tutorial k8s-context-switch
  sdd-propose sdd-apply sdd-verify sdd-review sdd-deliver sdd-orch
  cook-progress cook-meeting cook-messages
)
# Personal projects, writing, learning.
PERSONAL_SKILLS=(cook-blog-publish write-article promptlingo vocab openclaw)
# Present in the vault but not installable (e.g. no SKILL.md).
SKIP_SKILLS=(learned)

info() { printf '  %s\n' "$*"; }
run() {
  if [ "$DRY_RUN" = 1 ]; then printf '  DRY '; printf '%q ' "$@"; printf '\n'
  else "$@"; fi
}

in_list() {  # $1 = needle, rest = haystack
  local needle="$1"; shift
  local x
  for x in "$@"; do [ "$x" = "$needle" ] && return 0; done
  return 1
}

skipped_name() { in_list "$1" "${ALWAYS_SKIP[@]}"; }

skill_wanted() {  # $1 = skill dir name
  local n="$1"
  in_list "$n" "${SKIP_SKILLS[@]}" && return 1
  in_list "$n" "${COMMON_SKILLS[@]}" && return 0
  case "$PROFILE" in
    all)
      in_list "$n" "${WORK_SKILLS[@]}" && return 0
      in_list "$n" "${PERSONAL_SKILLS[@]}" && return 0 ;;
    work)
      in_list "$n" "${WORK_SKILLS[@]}" && return 0
      in_list "$n" "${PERSONAL_SKILLS[@]}" && return 1 ;;
    personal)
      in_list "$n" "${PERSONAL_SKILLS[@]}" && return 0
      in_list "$n" "${WORK_SKILLS[@]}" && return 1 ;;
  esac
  info "WARN unclassified skill, installing by default: $n"
  return 0
}

ensure_backup_dir() {  # $1 = subdir (category or "top")
  [ "$DRY_RUN" = 1 ] || mkdir -p "$BACKUP/$1"
}

backup_then_remove() {  # $1 = path to save + delete, $2 = backup subdir
  ensure_backup_dir "$2"
  # No `|| true` here on purpose: if the backup fails we must NOT delete.
  run cp -R "$1" "$BACKUP/$2/"
  run rm -rf "$1"
}

link_item() {  # $1 = real path in vault (SoT), $2 = link path under ~/.claude, $3 = backup subdir
  local src="$1" lnk="$2" sub="$3"
  if [ -L "$lnk" ] && [ "$(readlink "$lnk")" = "$src" ]; then
    return
  fi
  if [ -e "$lnk" ] || [ -L "$lnk" ]; then backup_then_remove "$lnk" "$sub"; fi
  run ln -s "$src" "$lnk"
}

points_into_vault() {  # $1 = symlink path
  case "$(readlink "$1")" in "$VAULT_CLAUDE"/*) return 0 ;; *) return 1 ;; esac
}

echo "== install.sh (DRY_RUN=$DRY_RUN, PROFILE=$PROFILE) =="
echo "   vault SoT : $VAULT_CLAUDE"
echo "   target    : $HOME_CLAUDE"
echo "   backup    : $BACKUP"
echo

for cat in "${CATEGORIES[@]}"; do
  vdir="$VAULT_CLAUDE/$cat"; hdir="$HOME_CLAUDE/$cat"
  echo "-- $cat/"
  run mkdir -p "$vdir"

  # 1) migrate real items from ~/.claude into the vault (dotfiles included)
  if [ -d "$hdir" ]; then
    for item in "$hdir"/* "$hdir"/.*; do
      name="$(basename "$item")"
      skipped_name "$name" && continue
      [ -e "$item" ] || [ -L "$item" ] || continue
      # generated by this script — machine-local, must never enter the vault
      [ "$cat/$name" = "$MACHINE_PATHS_REL" ] && continue

      # delete loose junk in skills/
      if [ "$cat" = skills ] && in_list "$name" "${SKILL_JUNK[@]}"; then
        info "delete junk: $cat/$name"; backup_then_remove "$item" "$cat"; continue
      fi

      [ -L "$item" ] && continue           # symlinks handled in steps 2/3
      if [ -e "$vdir/$name" ]; then
        info "dup -> vault wins, drop ~ copy: $cat/$name"; backup_then_remove "$item" "$cat"
      else
        info "migrate into vault: $cat/$name"
        ensure_backup_dir "$cat"; run cp -R "$item" "$BACKUP/$cat/"
        run cp -R "$item" "$vdir/$name"
        run rm -rf "$item"
      fi
    done
  fi

  # 2) per-item symlink every wanted vault item back into ~/.claude
  run mkdir -p "$hdir"
  for item in "$vdir"/*; do
    name="$(basename "$item")"
    skipped_name "$name" && continue
    if [ "$cat" = skills ] && ! skill_wanted "$name"; then continue; fi
    link_item "$item" "$hdir/$name" "$cat"
  done

  # 3) prune our own symlinks that this profile should not have
  if [ "$cat" = skills ] && [ -d "$hdir" ]; then
    for lnk in "$hdir"/*; do
      [ -L "$lnk" ] || continue
      points_into_vault "$lnk" || continue     # never touch links we did not make
      name="$(basename "$lnk")"
      if ! skill_wanted "$name"; then
        info "prune (not in PROFILE=$PROFILE): $cat/$name"
        run rm -f "$lnk"
      fi
    done
  fi
done

echo "-- top-level files"
for f in "${TOP_FILES[@]}"; do
  if [ -e "$HOME_CLAUDE/$f" ] && [ ! -L "$HOME_CLAUDE/$f" ] && [ ! -e "$VAULT_CLAUDE/$f" ]; then
    info "migrate into vault: $f"
    ensure_backup_dir top; run cp "$HOME_CLAUDE/$f" "$BACKUP/top/$f"
    run cp "$HOME_CLAUDE/$f" "$VAULT_CLAUDE/$f"
    run rm -f "$HOME_CLAUDE/$f"
  fi
  if [ -e "$VAULT_CLAUDE/$f" ]; then link_item "$VAULT_CLAUDE/$f" "$HOME_CLAUDE/$f" top; fi
done

echo "-- machine paths"
MP_OUT="$HOME_CLAUDE/$MACHINE_PATHS_REL"
if [ -e "$VAULT_CLAUDE/$MACHINE_PATHS_REL" ]; then
  echo "install.sh: $MACHINE_PATHS_REL must stay machine-local, but it exists in the vault." >&2
  echo "            Delete $VAULT_CLAUDE/$MACHINE_PATHS_REL and re-run." >&2
  exit 3
fi
TILDE='~'
info "generate: ${MP_OUT/#$HOME/$TILDE}"
if [ "$DRY_RUN" = 1 ]; then
  info "DRY (content: {base_url}=$VAULT_ROOT, {home}=$HOME, profile=$PROFILE)"
else
  mkdir -p "$(dirname "$MP_OUT")"
  sed -e "s|__VAULT__|$VAULT_ROOT|g" \
      -e "s|__HOME__|$HOME|g" \
      -e "s|__STAMP__|$STAMP|g" \
      -e "s|__PROFILE__|$PROFILE|g" > "$MP_OUT" <<'MPEOF'
# Machine Paths

Generated by `install.sh` at __STAMP__ for this machine. Machine-local: not tracked in the vault, never edit by hand — re-run `install.sh` instead.

Vault-tracked files never hardcode an absolute path. They write these placeholders. **Expand a placeholder to the value below before passing any path to a tool** — no tool accepts `{base_url}` literally.

| Placeholder  | This machine   |
| ------------ | -------------- |
| `{base_url}` | `__VAULT__`    |
| `{home}`     | `__HOME__`     |

Installed skill profile: `__PROFILE__`. Skills belonging to the other profile are deliberately absent from `~/.claude/skills/` — if one is missing, that is configuration, not breakage. Re-run `install.sh` with a different `PROFILE` to change it.
MPEOF
fi

echo
echo "== done (DRY_RUN=$DRY_RUN, PROFILE=$PROFILE). Re-run with DRY_RUN=0 to apply. =="
