#!/usr/bin/env bash
#
# install.sh — make this Obsidian vault's .claude and .codex the source of truth
#              for ~/.claude and ~/.codex
#
# Model: PER-ITEM symlinks. The vault holds the real files (git-tracked = SoT);
#        each ~/.claude/<category>/<item> and each top-level config file becomes a
#        symlink pointing into the vault. The whole ~/.claude dir is NEVER symlinked,
#        so runtime state (projects/, sessions/, cache/, credentials, plugins/, ...)
#        is untouched by construction.
#
# Paths: vault-tracked files never hardcode an absolute path — they write the
#        placeholders {base_url} (vault root) and {home}. This script resolves both
#        for THIS machine into ~/.claude/rules/00-machine-paths.md, which loads with
#        every session. That file is generated, machine-local, and never migrated
#        back into the vault.
#
# Links every skill in the vault — there is no per-machine selection. A symlink is
#        removed only when its vault target is gone or the name is on SKIP_SKILLS.
#
# Safe:  idempotent, backs up anything it replaces to ~/.claude/backups/install-<stamp>/,
#        and defaults to DRY-RUN. Apply with:  DRY_RUN=0 ./install.sh
#
set -euo pipefail
shopt -s nullglob

VAULT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VAULT_CLAUDE="$VAULT_ROOT/.claude"
VAULT_CODEX="$VAULT_ROOT/.codex"
CODEX_CONFIG_TMPL="$VAULT_ROOT/.codex-templates/config.toml.tmpl"
HOME_CLAUDE="$HOME/.claude"
HOME_CODEX="$HOME/.codex"
STAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP="$HOME_CLAUDE/backups/install-$STAMP"
DRY_RUN="${DRY_RUN:-1}"

# Category dirs linked per-item; single top-level config files linked individually.
CATEGORIES=(skills rules hooks agents commands)
TOP_FILES=(CLAUDE.md keybindings.json settings.json)
# Loose junk under skills/ to delete (not real skills — no own folder).
SKILL_JUNK=(SKILL.md STYLE_PRESETS.md)
# Never touched anywhere: noise, or generated by this script.
ALWAYS_SKIP=(. .. .DS_Store synced) # synced is a provider-managed runtime skill cache
MACHINE_PATHS_REL="rules/00-machine-paths.md"
# Never symlinked: machine-local by Claude Code convention.
# (settings.local.json is intentionally excluded from TOP_FILES above.)

# Every skill in the vault is installed. Only these are held back — present in the
# vault but not usable as skills (e.g. no SKILL.md).
SKIP_SKILLS=(learned)

info() { printf '  %s\n' "$*"; }
run() {
  if [ "$DRY_RUN" = 1 ]; then printf '  DRY '; printf '%q ' "$@"; printf '\n'
  else "$@"; fi
}

in_list() {  # $1 = needle, rest = haystack
  local needle="$1"; shift
  local x
  for x in "$@"; do [ "$x" = "$needle" ] && return 0; done
  return 1
}

skipped_name() { in_list "$1" "${ALWAYS_SKIP[@]}"; }

skill_installable() {  # $1 = skill dir name — false only for SKIP_SKILLS
  in_list "$1" "${SKIP_SKILLS[@]}" && return 1
  return 0
}

ensure_backup_dir() {  # $1 = subdir (category or "top")
  [ "$DRY_RUN" = 1 ] || mkdir -p "$BACKUP/$1"
}

backup_then_remove() {  # $1 = path to save + delete, $2 = backup subdir
  ensure_backup_dir "$2"
  # No `|| true` here on purpose: if the backup fails we must NOT delete.
  run cp -R "$1" "$BACKUP/$2/"
  run rm -rf "$1"
}

link_item() {  # $1 = real path in vault (SoT), $2 = link path under ~/.claude, $3 = backup subdir
  local src="$1" lnk="$2" sub="$3"
  if [ -L "$lnk" ] && [ "$(readlink "$lnk")" = "$src" ]; then
    return
  fi
  if [ -e "$lnk" ] || [ -L "$lnk" ]; then backup_then_remove "$lnk" "$sub"; fi
  run ln -s "$src" "$lnk"
}

points_into_vault() {  # $1 = symlink path
  case "$(readlink "$1")" in "$VAULT_CLAUDE"/*) return 0 ;; *) return 1 ;; esac
}

points_into_vault_any() {  # $1 = symlink path — matches .claude OR .codex vault dirs
  local target; target="$(readlink "$1")"
  case "$target" in "$VAULT_CLAUDE"/*|"$VAULT_CODEX"/*) return 0 ;; *) return 1 ;; esac
}

drop_stale_links() {  # $1 = dir under ~, $2 = label — remove our links whose target vanished
  [ -d "$1" ] || return 0
  local lnk
  for lnk in "$1"/*; do
    [ -L "$lnk" ] || continue
    points_into_vault_any "$lnk" || continue   # never touch links we did not make
    [ -e "$lnk" ] && continue                  # target still resolves
    info "drop stale link (gone from vault): $2/$(basename "$lnk")"
    run rm -f "$lnk"
  done
}

echo "== install.sh (DRY_RUN=$DRY_RUN) =="
echo "   vault SoT : $VAULT_CLAUDE"
echo "   target    : $HOME_CLAUDE"
echo "   backup    : $BACKUP"
echo

for cat in "${CATEGORIES[@]}"; do
  vdir="$VAULT_CLAUDE/$cat"; hdir="$HOME_CLAUDE/$cat"
  echo "-- $cat/"
  run mkdir -p "$vdir"

  # 1) migrate real items from ~/.claude into the vault (dotfiles included)
  if [ -d "$hdir" ]; then
    for item in "$hdir"/* "$hdir"/.*; do
      name="$(basename "$item")"
      skipped_name "$name" && continue
      [ -e "$item" ] || [ -L "$item" ] || continue
      # generated by this script — machine-local, must never enter the vault
      [ "$cat/$name" = "$MACHINE_PATHS_REL" ] && continue

      # delete loose junk in skills/
      if [ "$cat" = skills ] && in_list "$name" "${SKILL_JUNK[@]}"; then
        info "delete junk: $cat/$name"; backup_then_remove "$item" "$cat"; continue
      fi

      [ -L "$item" ] && continue           # symlinks handled in steps 2/3
      if [ -e "$vdir/$name" ]; then
        info "dup -> vault wins, drop ~ copy: $cat/$name"; backup_then_remove "$item" "$cat"
      else
        info "migrate into vault: $cat/$name"
        ensure_backup_dir "$cat"; run cp -R "$item" "$BACKUP/$cat/"
        run cp -R "$item" "$vdir/$name"
        run rm -rf "$item"
      fi
    done
  fi

  # 2) per-item symlink every wanted vault item back into ~/.claude
  run mkdir -p "$hdir"
  for item in "$vdir"/*; do
    name="$(basename "$item")"
    skipped_name "$name" && continue
    if [ "$cat" = skills ] && ! skill_installable "$name"; then continue; fi
    link_item "$item" "$hdir/$name" "$cat"
  done

  # 3) drop our own symlinks whose vault target is gone, or that are skip-listed
  drop_stale_links "$hdir" "$cat"
  if [ "$cat" = skills ] && [ -d "$hdir" ]; then
    for lnk in "$hdir"/*; do
      [ -L "$lnk" ] || continue
      points_into_vault_any "$lnk" || continue
      name="$(basename "$lnk")"
      skill_installable "$name" && continue
      info "drop link (skip-listed): $cat/$name"
      run rm -f "$lnk"
    done
  fi
done

echo "-- top-level files"
for f in "${TOP_FILES[@]}"; do
  if [ -e "$HOME_CLAUDE/$f" ] && [ ! -L "$HOME_CLAUDE/$f" ] && [ ! -e "$VAULT_CLAUDE/$f" ]; then
    info "migrate into vault: $f"
    ensure_backup_dir top; run cp "$HOME_CLAUDE/$f" "$BACKUP/top/$f"
    run cp "$HOME_CLAUDE/$f" "$VAULT_CLAUDE/$f"
    run rm -f "$HOME_CLAUDE/$f"
  fi
  if [ -e "$VAULT_CLAUDE/$f" ]; then link_item "$VAULT_CLAUDE/$f" "$HOME_CLAUDE/$f" top; fi
done

echo "-- machine paths"
MP_OUT="$HOME_CLAUDE/$MACHINE_PATHS_REL"
if [ -e "$VAULT_CLAUDE/$MACHINE_PATHS_REL" ]; then
  echo "install.sh: $MACHINE_PATHS_REL must stay machine-local, but it exists in the vault." >&2
  echo "            Delete $VAULT_CLAUDE/$MACHINE_PATHS_REL and re-run." >&2
  exit 3
fi
TILDE='~'
info "generate: ${MP_OUT/#$HOME/$TILDE}"
if [ "$DRY_RUN" = 1 ]; then
  info "DRY (content: {base_url}=$VAULT_ROOT, {home}=$HOME)"
else
  mkdir -p "$(dirname "$MP_OUT")"
  sed -e "s|__VAULT__|$VAULT_ROOT|g" \
      -e "s|__HOME__|$HOME|g" \
      -e "s|__STAMP__|$STAMP|g" > "$MP_OUT" <<'MPEOF'
# Machine Paths

Generated by `install.sh` at __STAMP__ for this machine. Machine-local: not tracked in the vault, never edit by hand — re-run `install.sh` instead.

Vault-tracked files never hardcode an absolute path. They write these placeholders. **Expand a placeholder to the value below before passing any path to a tool** — no tool accepts `{base_url}` literally.

| Placeholder  | This machine   |
| ------------ | -------------- |
| `{base_url}` | `__VAULT__`    |
| `{home}`     | `__HOME__`     |

MPEOF
fi

# =============================================================================
# Codex CLI — parallel structure for ~/.codex
# =============================================================================

echo
echo "== Codex CLI section =="
echo "   vault SoT : $VAULT_CODEX"
echo "   target    : $HOME_CODEX"
echo

# --- Codex: clean ECC remnants (first-run only) ----------------------------
CODEX_ECC_DIRS=(prompts git-hooks) # vendor_imports is a current Codex runtime cache
CODEX_ECC_FILES=(hooks.disabled.json)
ecc_found=0
for d in "${CODEX_ECC_DIRS[@]}"; do
  [ -d "$HOME_CODEX/$d" ] && ecc_found=1 && break
done
for f in "${CODEX_ECC_FILES[@]}"; do
  [ -e "$HOME_CODEX/$f" ] && ecc_found=1 && break
done
if [ "$ecc_found" = 1 ]; then
  echo "-- cleaning ECC remnants"
  ensure_backup_dir "codex-ecc"
  for d in "${CODEX_ECC_DIRS[@]}"; do
    [ -d "$HOME_CODEX/$d" ] || continue
    info "remove ECC dir: $d"
    backup_then_remove "$HOME_CODEX/$d" "codex-ecc"
  done
  for f in "${CODEX_ECC_FILES[@]}"; do
    [ -e "$HOME_CODEX/$f" ] || continue
    info "remove ECC file: $f"
    backup_then_remove "$HOME_CODEX/$f" "codex-ecc"
  done
fi

# The vault's Codex view shares the same skill originals as both home installs.
# A relative link keeps this alias portable when the vault moves to another machine.
echo "-- vault codex skills/ (shared source)"
run mkdir -p "$VAULT_CODEX"
link_item "../.claude/skills" "$VAULT_CODEX/skills" "vault-codex-skills"

# --- Codex: top-level symlinked files ---------------------------------------
CODEX_SYMLINK_FILES=(AGENTS.md hooks.json)
echo "-- codex top-level files (symlink)"
for f in "${CODEX_SYMLINK_FILES[@]}"; do
  if [ -e "$VAULT_CODEX/$f" ]; then
    link_item "$VAULT_CODEX/$f" "$HOME_CODEX/$f" "codex-top"
  fi
done

# --- Codex: config.toml (sed-generated, not symlinked) ----------------------
echo "-- codex config.toml (generated)"
if [ -e "$CODEX_CONFIG_TMPL" ]; then
  info "generate: ~/.codex/config.toml"
  if [ "$DRY_RUN" = 1 ]; then
    info "DRY (sed __HOME__=$HOME)"
  else
    if [ -e "$HOME_CODEX/config.toml" ] && [ ! -L "$HOME_CODEX/config.toml" ]; then
      ensure_backup_dir "codex-top"
      cp "$HOME_CODEX/config.toml" "$BACKUP/codex-top/config.toml"
    fi
    sed -e "s|__HOME__|$HOME|g" "$CODEX_CONFIG_TMPL" > "$HOME_CODEX/config.toml"
  fi
fi

# --- Codex: hooks/ (per-item symlink) ---------------------------------------
echo "-- codex hooks/"
run mkdir -p "$HOME_CODEX/hooks"
for item in "$VAULT_CODEX/hooks"/*; do
  [ -e "$item" ] || continue
  name="$(basename "$item")"
  skipped_name "$name" && continue
  link_item "$item" "$HOME_CODEX/hooks/$name" "codex-hooks"
done

# --- Codex: agents/ (copy, not symlink — #15345) ----------------------------
echo "-- codex agents/ (copy)"
run mkdir -p "$HOME_CODEX/agents"
for item in "$VAULT_CODEX/agents"/*; do
  [ -e "$item" ] || continue
  name="$(basename "$item")"
  skipped_name "$name" && continue
  dest="$HOME_CODEX/agents/$name"
  if [ -e "$dest" ] && diff -q "$item" "$dest" >/dev/null 2>&1; then
    continue  # already up to date
  fi
  if [ -e "$dest" ]; then
    ensure_backup_dir "codex-agents"
    run cp "$dest" "$BACKUP/codex-agents/$name"
  fi
  info "copy: agents/$name"
  run cp "$item" "$dest"
done

# --- Codex: skills/ (symlink from .claude/skills/) --------------------------
echo "-- codex skills/ (shared from .claude/skills/)"
run mkdir -p "$HOME_CODEX/skills"

# Link wanted skills from the Claude vault skills dir
for item in "$VAULT_CLAUDE/skills"/*; do
  [ -d "$item" ] || continue
  name="$(basename "$item")"
  skipped_name "$name" && continue
  skill_installable "$name" || continue
  link_item "$item" "$HOME_CODEX/skills/$name" "codex-skills"
done

# Drop our own links whose vault target is gone, or that are skip-listed
drop_stale_links "$HOME_CODEX/skills" "codex skills"
drop_stale_links "$HOME_CODEX/hooks" "codex hooks"
for lnk in "$HOME_CODEX/skills"/*; do
  [ -L "$lnk" ] || continue
  points_into_vault_any "$lnk" || continue
  name="$(basename "$lnk")"
  skill_installable "$name" && continue
  info "drop codex skill link (skip-listed): $name"
  run rm -f "$lnk"
done

echo
# Blog project instructions are generated copies; their originals stay in Vault.
BLOG_REPO="$HOME/code/personal/youruser-blog"
BLOG_CONFIG="$VAULT_CLAUDE/project-configs/youruser-blog/CLAUDE.md"
if [ -f "$BLOG_CONFIG" ] && [ -d "$BLOG_REPO" ]; then
  if [ ! -f "$BLOG_REPO/CLAUDE.md" ] || ! cmp -s "$BLOG_CONFIG" "$BLOG_REPO/CLAUDE.md"; then
    info "sync blog project CLAUDE.md from vault"
    if [ -f "$BLOG_REPO/CLAUDE.md" ]; then
      ensure_backup_dir blog-project
      run cp "$BLOG_REPO/CLAUDE.md" "$BACKUP/blog-project/CLAUDE.md"
    fi
    run cp "$BLOG_CONFIG" "$BLOG_REPO/CLAUDE.md"
  fi
fi

echo "== done (DRY_RUN=$DRY_RUN). Re-run with DRY_RUN=0 to apply. =="
