#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml"]
# ///
"""Scan local git repos under ~/code and (re)generate repos.yaml.

The vault lives in iCloud and syncs across Macs, so absolute paths (which embed
/Users/<username>/) are not portable. This script stores every repo as a
$HOME-relative path — resolvable on any machine via os.path.expanduser("~").

The `vault_project` overlay (curated repo -> vault note-project links) is
preserved across runs: it is read back from the existing repos.yaml, matched by
`path`, and re-attached. Everything else is derived from disk and overwritten.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import yaml

HOME = Path.home()
SCAN_ROOTS = ["code"]  # relative to $HOME
MAX_DEPTH = 5
REPOS_YAML = Path(__file__).resolve().parent.parent / "repos.yaml"


def git_remote(repo: Path) -> str | None:
    try:
        out = subprocess.run(
            ["git", "-C", str(repo), "remote", "get-url", "origin"],
            capture_output=True, text=True, timeout=10,
        )
        return out.stdout.strip() or None if out.returncode == 0 else None
    except (subprocess.SubprocessError, OSError):
        return None


def host_of(remote: str | None) -> str | None:
    """github.com:AcmeCorp/Repo.git -> 'github:AcmeCorp'."""
    if not remote:
        return None
    body = remote.split("://", 1)[-1].split("@", 1)[-1]  # strip scheme / user@
    body = body.replace(":", "/", 1)  # scp-style git@host:org -> host/org
    parts = [p for p in body.split("/") if p]
    if len(parts) < 2:
        return parts[0].split(".")[0] if parts else None
    host = parts[0].split(".")[0]  # github.com -> github
    org = parts[1]
    return f"{host}:{org}"


def find_repos() -> list[Path]:
    found: list[Path] = []
    for root_rel in SCAN_ROOTS:
        root = HOME / root_rel
        if not root.is_dir():
            continue
        base_depth = len(root.parts)
        for dirpath, dirnames, _ in os.walk(root):
            depth = len(Path(dirpath).parts) - base_depth
            if depth > MAX_DEPTH:
                dirnames[:] = []
                continue
            if ".git" in dirnames:
                found.append(Path(dirpath))
                dirnames.remove(".git")  # don't descend into .git
    return sorted(found)


CURATED_FIELDS = ("vault_project", "description")


def _overlay_key(remote: str | None, path: str) -> str:
    """Stable identity for carrying curated fields across scans. Prefer the
    remote URL — it survives local path changes (moves/renames); fall back to
    the $HOME-relative path for repos with no remote."""
    return remote or f"path:{path}"


def load_overlay() -> dict[str, dict]:
    """overlay key -> curated fields, from the existing repos.yaml (preserved
    across scans). Keyed by remote so moving repos on disk doesn't drop them."""
    if not REPOS_YAML.exists():
        return {}
    data = yaml.safe_load(REPOS_YAML.read_text(encoding="utf-8")) or {}
    overlay: dict[str, dict] = {}
    for r in data.get("repos", []):
        curated = {f: r[f] for f in CURATED_FIELDS if r.get(f)}
        if curated:
            overlay[_overlay_key(r.get("remote"), r["path"])] = curated
    return overlay


def main() -> None:
    overlay = load_overlay()
    repos = []
    for repo in find_repos():
        rel = repo.relative_to(HOME).as_posix()  # $HOME-relative, portable
        path = f"{rel}"
        remote = git_remote(repo)
        entry = {
            "name": repo.name,
            "path": path,
            "remote": remote,
            "host": host_of(remote),
        }
        curated = overlay.get(_overlay_key(remote, path))
        if curated:
            entry.update(curated)
        repos.append(entry)

    doc = {
        "note": "Auto-generated by scripts/scan.py. Paths are $HOME-relative. "
                "Curated fields (vault_project, description) are preserved across "
                "scans — keyed by `remote` so moving a repo on disk keeps them; "
                "re-run scan.py to refresh the rest.",
        "repos": repos,
    }
    REPOS_YAML.write_text(
        yaml.safe_dump(doc, allow_unicode=True, sort_keys=False, width=100),
        encoding="utf-8",
    )
    print(f"Wrote {len(repos)} repos to {REPOS_YAML}")


if __name__ == "__main__":
    main()
